-- [1] FETCH ALL THE PRODUCTS WHICH FALL UNDER ELECTRONICS CATEGORY - (USE PRODUCT & PRODUCT_CLASS CATEGORY)
SELECT * FROM product AS p
JOIN product_class AS pc 
ON p.PRODUCT_CLASS_CODE = pc.PRODUCT_CLASS_CODE
WHERE UPPER(PRODUCT_CLASS_DESC) =  'ELECTRONICS';

-- [2] FETCH ALL THE PRODUCTS WHICH HAVE NOT BEEN ORDERED YET
SELECT p.PRODUCT_ID, PRODUCT_DESC, PRODUCT_CLASS_CODE, PRODUCT_QUANTITY_AVAIL FROM product AS p
LEFT JOIN order_items AS oi
ON p.PRODUCT_ID = oi.PRODUCT_ID
WHERE oi.PRODUCT_QUANTITY IS NULL;

-- [3] WRITE A QUERY TO FETCH ALL THE PRODUCT CATEGORY DESCRIPTIONS WHOSE AVERAGE PRICE IS > 5000
SELECT PRODUCT_CLASS_DESC, ROUND(AVG(p.PRODUCT_PRICE), 4)AS AVG_Price FROM product_class AS pc
JOIN product AS p
ON pc.PRODUCT_CLASS_CODE = p.PRODUCT_CLASS_CODE
GROUP BY PRODUCT_CLASS_DESC
HAVING AVG_Price >5000;

-- [4] WRITE A QUERY TO GET ALL THE COLUMNS AND ROWS FROM BOTH ORDER_HEADER AND ORDER_ITEMS
-- MySQL DOES NOT SUPPORT FULL OUTER JOIN DIRECTLY INSTEAD IT IS DONE BY USING THE UNION CLAUSE
SELECT * FROM order_header AS oh
LEFT JOIN order_items AS oi
ON oh.ORDER_ID = oi.ORDER_ID
UNION
SELECT * FROM order_header AS oh
RIGHT JOIN order_items AS oi
ON oh.ORDER_ID = oi.ORDER_ID;