-- [1] FIND THE TOTAL NUMBER OF RECORDS IN THE PRODUCT TABLE
SELECT COUNT(*) FROM product;

-- [2.1] FETCH SUM OF PRODUCT PRICE AND AVERAGE PRODUCT PRICE FOR EACH PRODUCT_CLASS_CODE.
SELECT PRODUCT_CLASS_CODE, SUM(PRODUCT_PRICE) AS TOTAL_PRICE, AVG(PRODUCT_PRICE) AS AVG_PRICE FROM product
GROUP BY PRODUCT_CLASS_CODE;

-- [2.2] SELECT ONLY THE PRODUCT CLASSES THAT HAVE AN AVERAGE PRICE >= 4000
SELECT PRODUCT_CLASS_CODE, SUM(PRODUCT_PRICE) AS TOTAL_PRICE, AVG(PRODUCT_PRICE) AS AVG_PRICE FROM product
GROUP BY PRODUCT_CLASS_CODE
HAVING AVG_PRICE >= 4000;

-- [3] FETCH TOTAL NUMBER OF MALE AND FEMALE CUSTOMERS - (USE ONLINE_CUSTOMER TABLE)
SELECT CUSTOMER_GENDER, COUNT(CUSTOMER_GENDER) AS TOTAL_NUM FROM online_customer
GROUP BY CUSTOMER_GENDER;

-- [4] DISPLAY THE COUNT OF UNIQUE CITIES IN THE ADDRESS TABLE
SELECT  COUNT(DISTINCT CITY) AS UNIQUE_CITIES FROM address;

 