-- [1] DISPLAY ENTIRE DATA FROM PRODUCTS TABLE
SELECT * FROM product;

-- [2] DISPLAY ONLY ADDRESS_ID, CITY, STATE AND PINCODE COLUMNS FROM ADDRESS TABLE
SELECT ADDRESS_ID, CITY, STATE, PINCODE FROM address;

-- [3] DISPLAY UNIQUE CITIES IN THE ADDRESS TABLE
SELECT DISTINCT CITY FROM address;

-- [4] DELETE ALL THE RECORDS FROM PRODUCTS TABLE WHOSE PRODUCT_ID IS 99999
DELETE FROM product
WHERE PRODUCT_ID = 99999;
SELECT * FROM product;

-- [5] UPDATE THE PRICE OF ALL PRODUCTS IN THE PRODUCTS TABLE TO A 25% LESSER VALUE
-- SET SQL_SAFE_UPDATES = 0
SET SQL_SAFE_UPDATES = 0;
UPDATE product SET PRODUCT_PRICE = PRODUCT_PRICE * 0.75;
SELECT * FROM product;

-- [6] DISPLAY THE TOP 10 ROWS FROM ADDRESS TABLE
SELECT * FROM address LIMIT 10;