-- [1] DISPLAY ALL THE RECORDS FROM ADDRESS TABLE WHERE STATE = 'NY'
SELECT * FROM address
WHERE STATE = 'NY';

-- [2] FETCH THE RECORDS FROM THE ADDRESS TABLE FOR NY, CT AND AL STATES
SELECT * FROM address
WHERE STATE IN ('NY', 'CT', 'AL');

-- [3] FETCH THE RECORDS FROM THE ADDRESS TABLE WHERE STATE IS NOT NULL
SELECT * FROM address
WHERE STATE IS NOT NULL;

-- [4] FETCH THE RECORDS FROM ADDRESS TABLE WHERE CITY NAME STARTS WITH THE LETTER 'B'
SELECT * FROM address
WHERE CITY LIKE 'B%';

-- [5] FETCH THE RECORDS FROM ADDRESS TABLE WHERE CITY NAME CONTAINS EXACTLY 5 LETTERS
SELECT * FROM address
WHERE CITY LIKE '_____';

-- [6] FETCH ALL THE RECORDS FROM THE PRODUCTS TABLE WHOSE PRICE IS BETWEEN 5000 AND 10000
SELECT * FROM product
WHERE PRODUCT_PRICE BETWEEN 5000 AND 10000;

-- [7] FETCH ALL THE RECORDS FROM PRODUCTS TABLE WHERE PRODUCT PRICE IS LESS THAN 1000 AND QUANTITY AVAILABLE IS MORE THAN 100
SELECT * FROM product
WHERE PRODUCT_PRICE < 1000 AND PRODUCT_QUANTITY_AVAIL > 100;

-- [8] FETCH ALL THE RECORDS FROM PRODUCTS TABLE WHERE PRODUCT PRICE IS LESS THAN 1000 OR QUANTITY AVAILABLE IS LESS THAN 50
SELECT * FROM product
WHERE PRODUCT_PRICE < 1000 OR PRODUCT_QUANTITY_AVAIL < 50;